image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker 

stages:
  - build

build:
  stage: build
  script:
    - docker build --build-arg Version=$CI_COMMIT_TAG -t "$CI_REGISTRY_IMAGE:latest" -f Dockerfile .
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker images
    - docker ps
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags
  except:
    - main
