volumes:
  mongo:


services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    command: [ --noauth ]
    volumes:
      - mongo:/data/db

  server:
    image: ghcr.io/biometix/bqat-api:latest
    build:
      context: https://github.com/Biometix/bqat-api.git
    shm_size: '8gb'
    ports:
      - 8848:8848
    depends_on:
      - mongo
      - redis
    environment:
      MGO_URL: mongodb://mongo:27017/
      RDS_URL: redis://redis:6379/
      DATA: data/
    volumes:
      - ./data:/app/data
