volumes:
  mongo:


services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    command: [--noauth]
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    build:
      context: https://github.com/mongo-express/mongo-express.git
    ports:
      - 8081:8081
    depends_on:
      - server
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_SITE_COOKIESECRET: 'cookiesecret'
      ME_CONFIG_SITE_SESSIONSECRET: 'sessionsecret'

  server:
    image: bqat-api:latest
    restart: always
    build:
      context: .
      args:
        - DEV=true
      #   - VER_CORE=value
      #   - VER_API=value
    shm_size: 8gb
    ports:
      - 8848:8848
    healthcheck:
      test: curl --fail -s http://localhost:8848/info || sleep 30 && curl --fail -s http://localhost:8848/info || sleep 30 && curl --fail -s http://localhost:8848/info || kill 1
      timeout: 5m
      retries: 1
    depends_on:
      - mongo
      - redis
    environment:
      PORT: 8848
      DEBUG_MODE: YES
      MGO_URL: mongodb://mongo:27017/
      RDS_URL: redis://redis:6379/
      DATA: data/
    volumes:
      - ./data:/app/data
      - ./api:/app/api
      - ./bqat:/app/bqat
      - ./tests:/app/tests

